id: I1860460E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:53:18+00:00'
last_modified: '2022-06-08T13:03:59.095163+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ58534
  title: ཁམས་ཆེན་དུམ་པ་བཅུ་དྲུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4E68:
      image_group_id: I4CZ58763
      title: ''
      total_pages: 984
      order: 1
      base_file: 4E68.txt
    B804:
      image_group_id: I4CZ58764
      title: ''
      total_pages: 1094
      order: 2
      base_file: B804.txt
    407E:
      image_group_id: I4CZ58765
      title: ''
      total_pages: 974
      order: 3
      base_file: 407E.txt
    CE8D:
      image_group_id: I4CZ58766
      title: ''
      total_pages: 1012
      order: 4
      base_file: CE8D.txt
    445A:
      image_group_id: I4CZ58767
      title: ''
      total_pages: 838
      order: 5
      base_file: 445A.txt
    F7A4:
      image_group_id: I4CZ58768
      title: ''
      total_pages: 949
      order: 6
      base_file: F7A4.txt
    A55E:
      image_group_id: I4CZ58769
      title: ''
      total_pages: 930
      order: 7
      base_file: A55E.txt
    46ED:
      image_group_id: I4CZ58770
      title: ''
      total_pages: 1254
      order: 8
      base_file: 46ED.txt
    A8E5:
      image_group_id: I4CZ58771
      title: ''
      total_pages: 958
      order: 9
      base_file: A8E5.txt
    C6A2:
      image_group_id: I4CZ58772
      title: ''
      total_pages: 1072
      order: 10
      base_file: C6A2.txt
    8F1E:
      image_group_id: I4CZ58773
      title: ''
      total_pages: 968
      order: 11
      base_file: 8F1E.txt
    '3389':
      image_group_id: I4CZ58774
      title: ''
      total_pages: 1016
      order: 12
      base_file: 3389.txt
    58E4:
      image_group_id: I4CZ58775
      title: ''
      total_pages: 912
      order: 13
      base_file: 58E4.txt
    D873:
      image_group_id: I4CZ58776
      title: ''
      total_pages: 1038
      order: 14
      base_file: D873.txt
    6FFF:
      image_group_id: I4CZ58777
      title: ''
      total_pages: 982
      order: 15
      base_file: 6FFF.txt
    CF6A:
      image_group_id: I4CZ58778
      title: ''
      total_pages: 1086
      order: 16
      base_file: CF6A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
