id: P010366
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ58534
  title: ཁམས་ཆེན་དུམ་པ་བཅུ་དྲུག
  author: ''
  volumes:
    18b6fdc0c68f4d60aacc17688e315f23:
      image_group_id: I4CZ58763
      title: ''
      volume_number: 1
      total_pages: 984
      base_file: v001.txt
    5e20d31b1b0f4bfda793dded9fab6aa2:
      image_group_id: I4CZ58764
      title: ''
      volume_number: 2
      total_pages: 1094
      base_file: v002.txt
    3becc59ec0574f76833b7be1422e8506:
      image_group_id: I4CZ58765
      title: ''
      volume_number: 3
      total_pages: 974
      base_file: v003.txt
    340e5b24fab64862b41cce04f457c58a:
      image_group_id: I4CZ58766
      title: ''
      volume_number: 4
      total_pages: 1012
      base_file: v004.txt
    bc01cef69bbd48bc81737b8ff56c3339:
      image_group_id: I4CZ58767
      title: ''
      volume_number: 5
      total_pages: 838
      base_file: v005.txt
    09b2d56cee5a46328bfbd48f2a5cddeb:
      image_group_id: I4CZ58768
      title: ''
      volume_number: 6
      total_pages: 949
      base_file: v006.txt
    e658f357273c494a906a3f8fe1197cba:
      image_group_id: I4CZ58769
      title: ''
      volume_number: 7
      total_pages: 930
      base_file: v007.txt
    b50cb2c6fe79486987c763da61469dac:
      image_group_id: I4CZ58770
      title: ''
      volume_number: 8
      total_pages: 1254
      base_file: v008.txt
    cae2000defb149e2b309d4d9ca142419:
      image_group_id: I4CZ58771
      title: ''
      volume_number: 9
      total_pages: 958
      base_file: v009.txt
    b415f9b5b38941ac958002f8946d97a4:
      image_group_id: I4CZ58772
      title: ''
      volume_number: 10
      total_pages: 1072
      base_file: v010.txt
    dd04f1a210bc4a81999b2df57469021b:
      image_group_id: I4CZ58773
      title: ''
      volume_number: 11
      total_pages: 968
      base_file: v011.txt
    8d71a9516477462f985f90aafc703696:
      image_group_id: I4CZ58774
      title: ''
      volume_number: 12
      total_pages: 1016
      base_file: v012.txt
    110ff837f59549129c17c8d17bc4c45e:
      image_group_id: I4CZ58775
      title: ''
      volume_number: 13
      total_pages: 912
      base_file: v013.txt
    e9732e5f0a974ef7b7ab5a71dd751c48:
      image_group_id: I4CZ58776
      title: ''
      volume_number: 14
      total_pages: 1038
      base_file: v014.txt
    fa1d10b98ec240c2938762bcc8365354:
      image_group_id: I4CZ58777
      title: ''
      volume_number: 15
      total_pages: 982
      base_file: v015.txt
    0fc2d0e62fdb4ff0ae54ec5746d9e896:
      image_group_id: I4CZ58778
      title: ''
      volume_number: 16
      total_pages: 1086
      base_file: v016.txt
